[package]
name = "qrcode-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
image = "0.25.5"
libc = "0.2.171"
qrcode = "0.14.1"

[lib]
crate-type = ["cdylib"]

[profile.release]
strip = true
lto = true
panic = "abort"
opt-level = 3
